changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Exciting New Features 🎉
      labels:
        - feature
        - enhancement
    - title: Rework 💪
      labels:
        - chore
        - refactoring
    - title: Bugfixes 🐛
      labels:
        - bug
        - bugfix
    - title: Other Changes
      labels:
        - "*"
