name: CI

on:
  push:
    branches:
      - "**"
      - "master"

jobs:
  ci-on-ubuntu:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true
      - name: Test
        run: dotnet test src --logger "GitHubActions;report-warnings=false"
        env:
          fpl__login: ${{ secrets.fpl__login }}
          fpl__password: ${{ secrets.fpl__password }}
          HEROKU_REDIS_COPPER_URL: ${{ secrets.HEROKU_REDIS_COPPER_URL }}
