name: CI

on:
  push:
    branches:
      - "**"
      - "master"

jobs:
  ci-on-ubuntu:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.100"
      - name: Run './build/build.sh Test'
        run: ./build/build.sh Test
        env:
          fpl__login: ${{ secrets.fpl__login }}
          fpl__password: ${{ secrets.fpl__password }}
