name: deploy-to-prod

on:
  workflow_dispatch:

jobs:
  deploy-ubuntu-prod:
    name: deploy-to-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
          ref: ${{ github.head_ref }}
      - run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9
        with:
          useConfigFile: true
      - name: Build Function
        run: dotnet build ./src/FplBot.Functions -o ./output -c Release /p:Version=${{ steps.gitversion.outputs.fullSemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}
      - uses: pulumi/actions@v3
        id: pulumi
        with:
          command: up
          stack-name: Prod
          work-dir: ./src/FplBot.Infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy function to prod
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ steps.pulumi.outputs.FunctionName }}
          package: './output'
      - name: Build docker images
        run: |
          docker build -t registry.heroku.com/blank-fplbot/web --build-arg INFOVERSION=${{ steps.gitversion.outputs.informationalVersion }} --build-arg VERSION=${{ steps.gitversion.outputs.fullSemVer }} -f ./src/Dockerfile.web ./src
          docker build -t registry.heroku.com/blank-fplbot/eventpublisher --build-arg INFOVERSION=${{ steps.gitversion.outputs.informationalVersion }} --build-arg VERSION=${{ steps.gitversion.outputs.fullSemVer }} -f ./src/Dockerfile.eventpublisher ./src
          docker build -t registry.heroku.com/blank-fplbot/indexer --build-arg INFOVERSION=${{ steps.gitversion.outputs.informationalVersion }} --build-arg VERSION=${{ steps.gitversion.outputs.fullSemVer }} -f ./src/Dockerfile.indexer ./src
          docker build -t registry.heroku.com/blank-fplbot/eventhandler --build-arg INFOVERSION=${{ steps.gitversion.outputs.informationalVersion }} --build-arg VERSION=${{ steps.gitversion.outputs.fullSemVer }} -f ./src/Dockerfile.eventhandler ./src
      - uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_TOKEN }}
      - name: Push docker image to Heroku
        run: |
          docker push registry.heroku.com/blank-fplbot/web
          docker push registry.heroku.com/blank-fplbot/eventpublisher
          docker push registry.heroku.com/blank-fplbot/indexer
          docker push registry.heroku.com/blank-fplbot/eventhandler
      - name: Deploy to prod
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        run: heroku container:release web eventpublisher indexer eventhandler --app blank-fplbot
      - run: git log $(git describe --tags --abbrev=0)..HEAD --oneline
      - name: Generate CHANGELOG.md
        id: releasenotes
        run: |
          gh api repos/$GITHUB_REPOSITORY/releases/generate-notes \
          -f tag_name="${{ steps.gitversion.outputs.majorMinorPatch }}" \
          -q .body > CHANGELOG.md
          echo -e "\n\n" >> CHANGELOG.md
          git log $(git describe --tags --abbrev=0)..HEAD --oneline >> CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.gitversion.outputs.majorMinorPatch }}
          release_name: Release ${{ steps.gitversion.outputs.majorMinorPatch }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
