name: Release

on:
  push:
    branches:
      - "master"

jobs:
  ubuntu-16_04:
    name: ubuntu-16_04
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.100"
      - name: Run './build/build.sh PushDockerImage'
        run: ./build/build.sh PushDockerImage
        env:
          fpl__login: ${{ secrets.fpl__login }}
          fpl__password: ${{ secrets.fpl__password }}
          DockerHub_Username: ${{ secrets.DockerHub_Username }}
          DockerHub_Password: ${{ secrets.DockerHub_Password }}
